name: preview-small

on:
  push:
#    branches:
#      - "master"

jobs:
  preview-small:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          wget -qO - https://files.openscad.org/OBS-Repository-Key.pub | sudo apt-key add -
          echo 'deb http://download.opensuse.org/repositories/home:/t-paul/xUbuntu_20.04/ ./' | sudo tee --append /etc/apt/sources.list.d/openscad.list
          sudo apt-get update -qq
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y openscad-nightly tigervnc-standalone-server
          sudo ln -s /usr/bin/openscad-nightly /usr/bin/openscad
          sudo pip install svg.path==2.2

      - name: Generate Previews
        run: |
          #xvfb-run --auto-servernum --server-args "-screen 0 1024x768x24" ./scripts/genpreviews.sh
          Xvnc -geometry 1024x768 -depth 24 &
          ./scripts/genpreviews.sh

      - name: Publish Previews
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          keep_files: true
